# Generated by Django 4.2.7 on 2025-10-12 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_image', models.ImageField(upload_to='')),
                ('p_name', models.CharField(max_length=100)),
                ('p_description', models.CharField(max_length=1000)),
                ('p_category', models.CharField(choices=[('Medicine', 'Medicine'), ('Equipment', 'Equipment')], max_length=10)),
                ('p_cost', models.IntegerField()),
                ('p_count', models.IntegerField()),
                ('v_name', models.CharField(max_length=100)),
                ('v_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_cost', models.IntegerField(null=True)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.medicalaccessories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.medicalaccessories')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.bill')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='accessories',
            field=models.ManyToManyField(through='accessories.BillItem', to='accessories.medicalaccessories'),
        ),
        migrations.AddField(
            model_name='bill',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
