# Generated by Django 5.1.2 on 2025-10-17 16:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(help_text='Product name', max_length=100)),
                ('p_cost', models.DecimalField(decimal_places=2, help_text='Price in Taka', max_digits=10)),
                ('p_count', models.IntegerField(help_text='Stock quantity')),
                ('p_description', models.TextField(help_text='Product description')),
                ('p_image', models.ImageField(help_text='Product image', upload_to='products/')),
                ('v_name', models.CharField(help_text='Vendor/Brand name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='bill',
            name='accessories',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='billitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessory'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accessories.accessory'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'accessory')},
        ),
        migrations.DeleteModel(
            name='MedicalAccessories',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='total_cost',
        ),
    ]
